# Generated by Django 2.2.3 on 2019-07-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('time', models.CharField(max_length=200)),
                ('src', models.CharField(max_length=20)),
                ('dst', models.CharField(max_length=20)),
            ],
        ),
    ]
