# Generated by Django 2.2.3 on 2019-08-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_expanduser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Messages',
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chat', models.CharField(max_length=30)),
                ('messages', models.ManyToManyField(to='chat.Messages')),
                ('people', models.ManyToManyField(to='chat.ExpandUser')),
            ],
        ),
    ]
