# Generated by Django 2.2.3 on 2019-08-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20190827_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_friends_+', to='chat.UserProfile'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='people',
            field=models.ManyToManyField(to='chat.UserProfile'),
        ),
        migrations.DeleteModel(
            name='ExpandUser',
        ),
    ]
